export const API_URL = "https://cetcp.ztco.ly/api"
export const STORAGE_URL = "https://cetcp.ztco.ly/storage/courses-images"
export const USER_IMAGE = "https://cetcp.ztco.ly/storage/users-images"
export const LECTURES_VIDEOS = "https://cetcp.ztco.ly/storage/lectures-videos"
export const RESOURCE_URL = "https://cetcp.ztco.ly/storage/resources-files"