import Head from 'next/head'
import Hero from '../components/Hero'
import CoursesCards from '@/components/CoursesCards'
import SubHeader from '@/components/SubHeader'
import { Box } from '@chakra-ui/react'
import { useEffect, useState,useContext } from 'react'
import { AuthContext } from '@/context/AuthContext'
import { useRouter } from 'next/router'
import Loading from '@/components/Loading'

export default function Home() {
  const router = useRouter();
  const { user, isLoggedIn } = useContext(AuthContext);
  const [isLoading,setIsLoading] = useState(true);

  useEffect(() => {
    if (isLoggedIn && typeof(user) !== "undefined") {
      if (user.type === "trainer") {
        router.push("/instructor/courses");
      } else {
        setIsLoading(false);
      }
    } else { 
      setIsLoading(false);
    }

  }, [user])
  
  if (isLoading) {
    return <Loading></Loading>
  }
  return (
    <>
      <Head>
        <title>CETEP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
      {isLoading ? <Loading></Loading> : 
      <>
        <Hero></Hero>
        <SubHeader></SubHeader>
          <CoursesCards/></> }
        <Box height="100px"/>
      </main>
    </>
  )
}
