import Head from 'next/head'
import { Inter } from 'next/font/google'
import Hero from '../components/Hero'
import CoursesCards from '@/components/CoursesCards'
import SubHeader from '@/components/SubHeader'
import { Box } from '@chakra-ui/react'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>CETEP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Hero></Hero>
        <SubHeader></SubHeader>
        <CoursesCards></CoursesCards>
        <Box height="100px"/>
      </main>
    </>
  )
}
