import Head from 'next/head'
import { Inter } from 'next/font/google'
import Hero from '../components/Hero'
import CoursesCards from '@/components/CoursesCards'
import SubHeader from '@/components/SubHeader'
import { Box } from '@chakra-ui/react'
import { useEffect, useState } from 'react'
import { redirect } from 'next/navigation'
async function getUserData(token) {
  return await fetch(`${URL.API_URL}/user-show`, {
    headers: {'Authorization': `Bearer ${token}`} })
  .then(res => res.json())
}

export default function Home() {
  const [render , setRender] = useState(false)

  useEffect(() => {
    if (localStorage.getItem("token") != "null") {
      console.log(localStorage.getItem("token"));
      getUserData(localStorage.getItem("token")).then((data) => {
        if (data.data.type == "trainer") {
          redirect("/instructor/courses")
        }
      });
    }
    setRender(true)
  }, [])

  return (
    <>
      <Head>
        <title>CETEP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Hero></Hero>
        <SubHeader></SubHeader>
        {render && <CoursesCards/>}
        <Box height="100px"/>
      </main>
    </>
  )
}
